return table.freeze({
	--// TextFaces //--
	faceNormal = Font.new("rbxassetid://16658221428", Enum.FontWeight.Medium, Enum.FontStyle.Normal),
	faceBold = Font.new("rbxassetid://16658221428", Enum.FontWeight.Bold, Enum.FontStyle.Normal),

	--// TextSizes //--
	text2xl = 22,
	textmd = 16,
	textsm = 15,

	--// Colors //--
	bgPageTheme = Color3.fromHex("#58978d"),

	bgGray = Color3.fromHex("f7f7f7"),

	bgWhite = Color3.fromHex("ffffff"),
	bgBlack = Color3.fromHex("000000"),

	--// Borders //--
	roundedxl = UDim.new(0, 12),
	rounded4xl = UDim.new(0, 32),
})
